/**
 * @file Help 帮助
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import { ISvgIconProps, IconWrapper } from '../runtime'

export default IconWrapper('help', true, (props: ISvgIconProps) => (
  <svg width={props.size} height={props.size} viewBox='0 0 48 48' fill='none'>
    <path
      d='m24.000046,31.160978l0,-5.902081c4.889362,0 8.853054,-3.96368 8.853054,-8.853048c0,-4.88946 -3.963692,-8.853135 -8.853054,-8.853135c-4.88945,0 -8.853146,3.963675 -8.853146,8.853135'
      stroke={props.colors[0]}
      stroke-width={props.strokeWidth}
      stroke-linecap={props.strokeLinecap}
      stroke-linejoin={props.strokeLinejoin}
    />
    <path
      fill-rule='evenodd'
      clip-rule='evenodd'
      d='m24,44.614437c1.794836,0 3.249882,-1.455036 3.249882,-3.249874c0,-1.794838 -1.455046,-3.249889 -3.249882,-3.249889c-1.794842,0 -3.249882,1.455051 -3.249882,3.249889c0,1.794838 1.45504,3.249874 3.249882,3.249874z'
      fill={props.colors[0]}
    />
  </svg>
))
