// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AOption: typeof import('@arco-design/web-vue')['Option']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    Button: typeof import('./components/ui/button/button.vue')['default']
    Tile: typeof import('./components/ui/settings/tile.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}

export { }
