// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    SettingsContainer: typeof import('./components/ui/settings/SettingsContainer.vue')['default']
    SettingsTile: typeof import('./components/ui/settings/SettingsTile.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}

export { }
