export { default as Home } from './icons/Home'
export { default as Left } from './icons/Left'
export { default as Right } from './icons/Right'
export { default as Windmill } from './icons/Windmill'
export { default as CloseSmall } from './icons/CloseSmall'
export { default as Help } from './icons/Help'
