#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# https://github.com/SalhiYassine/next-ts-template/blob/main/.husky/pre-commit

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔 Trying to build now. 🤔🤔🤔🤔'

yarn run prebuild ||
(
  echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
    Next build failed: View the errors above to see why. 
  '
  false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
